# This is a basic workflow to help you get started with Actions

name: Arduino Superheterodyne - CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        with:
          submodules: recursive

      # Use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # Install the platform.
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          
      # Compiling the sketch
      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:avr:uno ./arduino/arduinosuperhet
